packadd! onedark.vim

"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

" Use onedark
syntax on
colorscheme onedark

let mapleader=","

set hidden " hides buffers instead of closing

set tabstop=4 " number of visual spaces per TAB
set softtabstop=4 " number of spaces in tab when editing
set expandtab " tabs are spaces
filetype indent on " load filetype-specific indent files

set number " show line numbers
set showcmd " show command in bottom bar
set cursorline " highlight current line


set showmatch " highlight matching [{()}]
set hlsearch " highlight all results
set incsearch " show search results as you type

set path=.,** " search through all sub-directories (recursively) when searching for a file
set wildmenu " display all matching files when tab-completing

set smartcase " ignore case unless there is a capital letter in the search string

set wildignore=*.swp,*.bak,*pyc " ignore files with these extensions
set wildignore+=*/node_modules/*,*.min.js,*.esm.js,*.legacy.js " ignore node modules and other JS files from search

" Edit and load vim rc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR> 
inoremap jk <ESC>
" Remove trailing whitespace 
nnoremap <silent> <leader>rw :let _s=@/ <Bar> :%s/\s\+$//e <Bar> :let @/=_s <Bar> :nohl <Bar> :unlet _s <CR>

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor
endif
